### ISSUE TITLE
 Potential for Controversy in Generation

### ISSUE THREAD

**Issue by HaShaWB** [meta-llama/llama3#119]
It appears that LLAMA may not sufficiently understand East Asian cultures. Notably, when the term 'Korean' is mentioned, the model occasionally uses Japanese or Chinese greetings. Furthermore, when requested to generate responses in Korean, the outputs sometimes contain a mix of Chinese or Japanese elements, which could lead to controversy.

**Comment by subramen** [comment]
Thank you for pointing this out! Even though the tokenizer has multilingual vocabulary, currently Llama3 doesn't support multilingual inference. Currently the models are officially supported for inference in English, but as @thusinh1969 mentions, finetuning is an option here. We have an example using Llama 2 here : https://github.com/meta-llama/llama-recipes/tree/main/recipes/multilingual
