### ISSUE TITLE
Unable to process request to download the llama3 model

### ISSUE THREAD

**Issue by AnandUgale** [meta-llama/llama3#125]
Sorry, we could not process your request at this moment.
Request ID: 429478326339039

**Comment by bsariturk** [comment]
Same for me. I've been trying for a few days.

**Comment by ed1d1a8d** [comment]
Did you previously sign up using the same email for Llama-2 access. This happened to me and I also got an error:
![image](https://github.com/meta-llama/llama3/assets/1733389/2ff50b19-6e77-449b-b752-78ec4e0d028a)

I resolved the error by typing "Massachusetts Institute of Technology" instead of "MIT" in the affiliation field. I think possibly because the former is what I used when I requested Llama-2 access.

**Comment by AnandUgale** [comment]
> Did you previously sign up using the same email for Llama-2 access? I did and I also got an error: ![image](https://private-user-images.githubusercontent.com/1733389/326064193-2ff50b19-6e77-449b-b752-78ec4e0d028a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTM2ODksIm5iZiI6MTcxNDE1MzM4OSwicGF0aCI6Ii8xNzMzMzg5LzMyNjA2NDE5My0yZmY1MGIxOS02ZTc3LTQ0OWItYjc1Mi03OGVjNGUwZDAyOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTc0MzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM3N2QwOTRhN2RlZDRjNWI2NTc0OGEzMGRhMjUxODgxNzUwOWE2OGM5ZTU1ODdlNDIyOWExNzkzNmZjY2JjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JDNFwcrDHgGd8uciTtuNXFproJPvQ0OYbkh1vpiQQUI)
> 
> I resolved the error by typing "Massachusetts Institute of Technology" instead of "MIT" in the affiliation field. I think possibly because the former is what I used when I requested Llama-2 access. Maybe your information has to match exactly in order for the form to go through.


I tried it once again by changing the affiliation field as you suggested, and it worked! Thank you!

**Comment by avinashmyerolkar** [comment]
HTTP request sent, awaiting response... 403 Forbidden
2024-06-09 18:09:27 ERROR 403: Forbidden.

while downloading the meta llama 3 model
