### ISSUE TITLE
./LICENSE: Permission denied

### ISSUE THREAD

**Issue by ryzeto** [meta-llama/llama3#140]
I just got the URL and after running `download.sh` with GIT and entering the model I want I get `./LICENSE: Permission denied`. Any tips?

**Comment by yohlimem** [comment]
Have you found a fix?

**Comment by ryzeto** [comment]
No. I also tried on huggingface and same issue. Also for llama2 same issue

**Comment by samuelselvan** [comment]
@ryzeto are you still facing issues?

**Comment by samuelselvan** [comment]
Please free to re-open if still facing issues.
