### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by Jerry-hyl** [meta-llama/llama3#142]
I have already applied for access to meta llama3. And I also receive the email about how can I use download scripts to download it, but I still cannot have access to llama3 on huggingface.

**Comment by samuelselvan** [comment]
Can you share your hf user ids?

**Comment by samuelselvan** [comment]
@Jerry-hyl please feel free to re-open with with your hf user id if still facing issues.

**Comment by HenryStephen** [comment]
I had the same question. My hf id is Henry65. Please

**Comment by ZhenbinChen-NLP** [comment]
I had the same question. My hf id is ZhenbinChan.

**Comment by ryukato** [comment]
I also have same issue with downloading.
