### ISSUE TITLE
Does llama3 still not support SSE?

### ISSUE THREAD

**Issue by bzdx** [meta-llama/llama3#160]
here is my Node.js codes:

`const axios = require('axios');
const EventSource = require('eventsource');

const data = {
  model: "llama3",
  messages: [
    {
      role: "user",
      content: "hey!",
    },
  ],
  stream: false,
};

async function send() {
  try {
    let messages = encodeURIComponent(JSON.stringify(data.messages))
    let url = `http://localhost:11434/api/chat?model=${data.model}&stream=${data.stream}&messages=${messages}`
    const eventSource = new EventSource("");

    eventSource.onmessage = function(event) {
      const eventData = JSON.parse(event.data);
      console.log("Received message:", eventData);
    };

    eventSource.onerror = function(error) {
      console.error("EventSource failed:", error);
    };
  } catch (error) {
    console.error("Error:", error);
  }
}

send();
`

and the result is: 
`EventSource failed: Event { type: 'error', message: '' }`

I can't send SSE request to ollama server but I can send post request, why?

**Comment by subramen** [comment]
Hi! Since your question is related to ollama, please ask this on the ollama repository. This repo is only related to the llama3 model inference.
