### ISSUE TITLE
【Error】Unable to download Llama3: RROR 403: Forbidden

### ISSUE THREAD

**Issue by wqw547243068** [meta-llama/llama3#166]
Though follow all the steps on the [page](https://llama.meta.com/llama-downloads)
- location is Singpore, gmail

![image](https://github.com/meta-llama/llama3/assets/3257257/0963e579-670e-4086-b3bf-3519cb9e3bb9)

![image](https://github.com/meta-llama/llama3/assets/3257257/e20b0519-5609-4d1e-a076-fb6b2df6a74b)

[download.sh](https://github.com/meta-llama/llama3/blob/main/download.sh)

```sh
bash download.sh
```

Got the error below

```
Resolving download6.llamameta.net (download6.llamameta.net)... 64:ff9b::12f5:3c76, 64:ff9b::12f5:3c04, 64:ff9b::12f5:3c2c, ...
Connecting to download6.llamameta.net (download6.llamameta.net)|64:ff9b::12f5:3c76|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-04-28 16:52:20 ERROR 403: Forbidden.
```

**Comment by Xtj1999** [comment]
same

**Comment by missfmaster** [comment]
是他妈了个逼的长城防火墙的问题。
```
正在连接 127.0.0.1:1087... 已连接。
已发出 Proxy 请求，正在等待回应... 200 OK
长度：16060617592 (15G) [binary/octet-stream]
正在保存至: “./Meta-Llama-3-8B-Instruct/consolidated.00.pth”

-8B-Instruct/consolidated.00.pth     0%[                                                                 ]  25.49M  26.5KB/s  剩余 6h 13m
```
他妈了个逼的，还得让老子花钱买VPN，狗日的玩意。

**Comment by wqw547243068** [comment]
Download successfully with VPN

**Comment by MacJayLee** [comment]
> 是他妈了个逼的长城防火墙的问题。
> 
> ```
> 正在连接 127.0.0.1:1087... 已连接。
> 已发出 Proxy 请求，正在等待回应... 200 OK
> 长度：16060617592 (15G) [binary/octet-stream]
> 正在保存至: “./Meta-Llama-3-8B-Instruct/consolidated.00.pth”
> 
> -8B-Instruct/consolidated.00.pth     0%[                                                                 ]  25.49M  26.5KB/s  剩余 6h 13m
> ```
> 
> 他妈了个逼的，还得让老子花钱买VPN，狗日的玩意。

唉 真是他妈个比的一言难尽

**Comment by walkingleo** [comment]
> 是他妈了个逼的长城防火墙的问题。
> 
> ```
> 正在连接 127.0.0.1:1087... 已连接。
> 已发出 Proxy 请求，正在等待回应... 200 OK
> 长度：16060617592 (15G) [binary/octet-stream]
> 正在保存至: “./Meta-Llama-3-8B-Instruct/consolidated.00.pth”
> 
> -8B-Instruct/consolidated.00.pth     0%[                                                                 ]  25.49M  26.5KB/s  剩余 6h 13m
> ```
> 
> 他妈了个逼的，还得让老子花钱买VPN，狗日的玩意。

有 VPN 了也不行呢？头大

**Comment by jingxdy** [comment]
想问下，是vpn模式不对吗，我也有vpn，但是也不行，还是报403

**Comment by Xtj1999** [comment]
VPN好像需要开全局，然后IP到美国

**Comment by tangxueduo** [comment]
> 是他妈了个逼的长城防火墙的问题。
> 
> ```
> 正在连接 127.0.0.1:1087... 已连接。
> 已发出 Proxy 请求，正在等待回应... 200 OK
> 长度：16060617592 (15G) [binary/octet-stream]
> 正在保存至: “./Meta-Llama-3-8B-Instruct/consolidated.00.pth”
> 
> -8B-Instruct/consolidated.00.pth     0%[                                                                 ]  25.49M  26.5KB/s  剩余 6h 13m
> ```
> 
> 他妈了个逼的，还得让老子花钱买VPN，狗日的玩意。
hhhhhhhhh最后解决了么

**Comment by tangxueduo** [comment]
![image](https://github.com/user-attachments/assets/75051287-245e-4175-bc70-a56cc9b8ec16)
me too

**Comment by 18069406914** [comment]
> 想问下，是vpn模式不对吗，我也有vpn，但是也不行，还是报403

解决了吗？

**Comment by LLUckkk** [comment]
I've used VPN but it doesn's work...
If it is neccessary to set the VPN to American?

**Comment by LLUckkk** [comment]
> True...... VPN is all you need . what can i say
想问下是什么VPN呀
