### ISSUE TITLE
Unable to get access from HF and Meta Llama 3 webpages

### ISSUE THREAD

**Issue by PerifanosPrometheus** [meta-llama/llama3#184]
Hello All,

I have requested access to Llama 3 both on HF and meta website around May 18 which is more than two weeks ago. When I try to request access from the meta website I get the following error message:
<img width="583" alt="image" src="https://github.com/meta-llama/llama3/assets/69210497/771bd885-7d6a-494a-a094-ed2f3038af8c">

On HF, the request seems to be stuck in a waiting for approval status.

I am not really sure what's going on and I would like to obtain more information regarding my options to get access as I am really eager to start experimenting with the model : )

I am really sorry for reaching out by creating an issue within the github repo but I tried connecting with people on HF via creation of this [HF discussion](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/discussions/81#6631909cd0bfdb97d2c22355) and commenting on [this discussion](https://huggingface.co/meta-llama/Meta-Llama-3-8B/discussions/47#662820bcf2b12d4e79977663) and [this other discussion](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/discussions/50#6627dcda26fb79861827db22) without any luck.

This is [my HF profile](https://huggingface.co/GiorgioDiSalvo). I am happy to provide any additional information as needed.

**Comment by samuelselvan** [comment]
@PerifanosPrometheus do you mind submitting another request? https://llama.meta.com/llama-downloads

**Comment by samuelselvan** [comment]
Please re-open if still needed.
