### ISSUE TITLE
failed: Bad file descriptor

### ISSUE THREAD

**Issue by 1634514080** [meta-llama/llama3#195]
I run bash download.sh in windows cmd and got this error: Connecting to 127.0.0.1:1080... failed: Bad file descriptor. What should i do?

Enter the URL from email: https://download6.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoib2RlanI4ZnFiaGJnMXR0c3picGFhc2U4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQ2LmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTUxNzY3MjF9fX1dfQ__&Signature=CZtzlqKWvxU6HLhpl-ofhPVfIF-Gw3kuKvRjOW%7E8fBaBJ50-B7ct0jZbaN97ak3NRGdpHcgk-UbsodwdjVrriQkRLO5HD1G%7EILGADfRy%7EygYy5VoSkir7Fr%7EW99okBAuaMycciPR8yvdrwOf7kY4HCA5qL1-50j69O7H2ycclMpSFV0Iyg33fccqav0GmJEIlVE5kBxyeL-3DN7KRBw6gDSMkwsKFz0rc9cCLrZJXp5j3ivd3q%7Ek-%7ETVZqPgCWUYsSh%7EkiPbdHxGb7cwWaz5uErfsoChulA9r-ZIWXRGQG46z-MDuJaxt-FWlxjX3HRU8GYyI0r3zCT5SozIVR3pjA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1488011928788012

Enter the list of models to download without spaces (8B,8B-instruct,70B,70B-instruct), or press Enter for all: 8B
Downloading LICENSE and Acceptable Usage Policy
--2024-05-08 00:19:28--  https://download6.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoib2RlanI4ZnFiaGJnMXR0c3picGFhc2U4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQ2LmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTUxNzY3MjF9fX1dfQ__&Signature=CZtzlqKWvxU6HLhpl-ofhPVfIF-Gw3kuKvRjOW~8fBaBJ50-B7ct0jZbaN97ak3NRGdpHcgk-UbsodwdjVrriQkRLO5HD1G~ILGADfRy~ygYy5VoSkir7Fr~W99okBAuaMycciPR8yvdrwOf7kY4HCA5qL1-50j69O7H2ycclMpSFV0Iyg33fccqav0GmJEIlVE5kBxyeL-3DN7KRBw6gDSMkwsKFz0rc9cCLrZJXp5j3ivd3q~k-~TVZqPgCWUYsSh~kiPbdHxGb7cwWaz5uErfsoChulA9r-ZIWXRGQG46z-MDuJaxt-FWlxjX3HRU8GYyI0r3zCT5SozIVR3pjA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1488011928788012
Connecting to 127.0.0.1:1080... failed: Bad file descriptor.
--2024-05-08 00:19:30--  https://download6.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoib2RlanI4ZnFiaGJnMXR0c3picGFhc2U4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQ2LmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MTUxNzY3MjF9fX1dfQ__&Signature=CZtzlqKWvxU6HLhpl-ofhPVfIF-Gw3kuKvRjOW%7E8fBaBJ50-B7ct0jZbaN97ak3NRGdpHcgk-UbsodwdjVrriQkRLO5HD1G%7EILGADfRy%7EygYy5VoSkir7Fr%7EW99okBAuaMycciPR8yvdrwOf7kY4HCA5qL1-50j69O7H2ycclMpSFV0Iyg33fccqav0GmJEIlVE5kBxyeL-3DN7KRBw6gDSMkwsKFz0rc9cCLrZJXp5j3ivd3q%7Ek-%7ETVZqPgCWUYsSh%7EkiPbdHxGb7cwWaz5uErfsoChulA9r-ZIWXRGQG46z-MDuJaxt-FWlxjX3HRU8GYyI0r3zCT5SozIVR3pjA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1488011928788012
Connecting to 127.0.0.1:1080... failed: Bad file descriptor.

**Comment by Arwindhraj** [comment]
```
Enter the list of models to download without spaces (8B,8B-instruct,70B,70B-instruct), or press Enter for all: 8B
Downloading LICENSE and Acceptable Usage Policy
Connecting to download6.llamameta.net (108.159.15.24:443)
wget: server returned error: HTTP/1.1 416 Requested Range Not Satisfiable
```
I encountered this issue while attempting to download. I then proceeded to download all the files, and now the pretrained models are downloading.
```
Enter the list of models to download without spaces (8B,8B-instruct,70B,70B-instruct), or press Enter for all:
Downloading LICENSE and Acceptable Usage Policy
Connecting to download6.llamameta.net (108.159.15.24:443)
LICENSE              100% |************************************************************************|  7744  0:00:00 ETA
Connecting to download6.llamameta.net (108.159.15.24:443)
USE_POLICY           100% |************************************************************************|  8800  0:00:00 ETA
Downloading 8b_pre_trained
Connecting to download6.llamameta.net (108.159.15.24:443)
consolidated.00.pth   55% |*****************************************************************************************    | 8453M  0:20:07 ETA
```
Try downloading all the files ones.

**Comment by samuelselvan** [comment]
@1634514080 I see "Connecting to 127.0.0.1:1080" instead of download<>.llamameta.net. Is there a proxy that you are using?

**Comment by samuelselvan** [comment]
Please feel to re-open if needed. Thanks.
