### ISSUE TITLE
Why are the parameters of llama3 model.py and llama2 model.py the same?

### ISSUE THREAD

**Issue by programmer-lxj** [meta-llama/llama3#204]
@dataclass
class ModelArgs:
    dim: int = 4096
    n_layers: int = 32
    n_heads: int = 32
    n_kv_heads: Optional[int] = None
    vocab_size: int = -1  # defined later by tokenizer
    multiple_of: int = 256  # make SwiGLU hidden layer size multiple of large power of 2
    ffn_dim_multiplier: Optional[float] = None
    norm_eps: float = 1e-5

    max_batch_size: int = 32
    max_seq_len: int = 2048

Why are the parameters of llama3 model.py also the same as llama2 model.py?    Isn’t the context length of llama3 8k? It looks like 4k above.

**Comment by subramen** [comment]
The 4k refers to the dimensionality of the model's layers, not the context length
