### ISSUE TITLE
Words/phrases/outputs in regional languages need to be examined for accuracy

### ISSUE THREAD

**Issue by nav9** [meta-llama/llama3#208]
I'm posting this here since I did not find any other venue for reporting errors. You have various pages like [this](https://llama.meta.com/responsible-use-guide/) and [this](https://llama.meta.com/trust-and-safety/). It would help to include links or forms on those pages for users to submit bug reports or errors they notice.  
  
## Describe the bug
Llama3's 70b instruct groq model incorrectly interpreted a word (`thevidichi`) in a regional language as positive, even though it is actually negative. ChatGPT 3.5 correctly recognized it as negative. Even a Google search shows the word has a negative connotation.    
  
### Minimal reproducible example
Use the prompt `meaning of malayalam word 'thevidichi'`.
  
### Output
`The word "Thevidichi" is a term of endearment and respect...`
  
![thevidichi](https://github.com/meta-llama/llama3/assets/2093933/25590fb6-e215-4cb0-a85b-c5fd6e892bab)

## Runtime Environment
- Model: Meta Llama-3-70b-instruct-groq
- Using via huggingface?: No
- OS: Mint
- GPU VRAM: Not applicable
- Number of GPUs: Not applicable
- GPU Make: Not applicable

**Additional context**
It was a word I encountered while watching an old Malayalam family movie, where the heroine calls herself the word, to prevent the hero from falling in love with her. Mentioning this context was necessary to emphasize the neutral/innocent reason for asking the LLM the meaning of the word.

**Comment by subramen** [comment]
Thanks for reporting this, you are welcome to open github issues to report any other bugs you may encounter :)

Multilingual support is coming soon for Llama - although it can recognize words from different languages it hasn't been specifically finetuned to support them (yet).

**Comment by mohblnk** [comment]
@subramen thanks for your info, just a quick a couple of question regarding Multilingual support;
* Will that means the model will be train/retrained on non-English data? 
* Are there an ETA of such a model?

**Comment by subramen** [comment]
No ETA yet, but please stay tuned for updates.
