### ISSUE TITLE
Issue of downloading models

### ISSUE THREAD

**Issue by Jimmy-Hu** [meta-llama/llama3#209]
I am trying to follow the instructions in readme to run the download.sh script. I pasted the URL in Email and the script terminated with the following error message:

```
Enter the URL from email: https://download6.llamameta.net/*...

Enter the list of models to download without spaces (8B,8B-instruct,70B,70B-instruct), or press Enter for all: <I press Enter here>
download.sh: 14: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 19: Bad substitution

```

Please help me to deal with this issue.

## Runtime Environment
- OS: Linux Ubuntu 6.5.0-28-generic #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by a492557688** [comment]
I also encountered this problem  。This is because some syntax of wget is not compatible on Ubuntu。Try using /bin/bash download.sh  This issue does not occur

**Comment by hybotix** [comment]
I am trying to complete an Arm Learning Path: https://learn.arm.com/learning-paths/embedded-systems/rpi-llama3 which is broken at the place where a download.sh script is expected. How can I properly download lllama 3.2 and continue with this procedure?
