### ISSUE TITLE
Model download error in Windows

### ISSUE THREAD

**Issue by Arwindhraj** [meta-llama/llama3#211]
I am trying to Download Llama3 8B in windows, i am using Windows PowerShell bash feature and trying to run download.sh file, it ask me for the URL that's valid for 24hrs provided by MetaAI at https://llama.meta.com/llama-downloads/

I tried several times, i getting same error multiple times , help me to solve

### Followed these steps:

HOW TO DOWNLOAD THE MODEL
Based on the model you requested, please visit the respective Github repository to run the download.sh script - [Llama 3](https://github.com/meta-llama/llama3), [Llama 2](https://github.com/meta-llama/llama), [Code Llama](https://github.com/meta-llama/codellama), or [Llama Guard](https://github.com/meta-llama/PurpleLlama). Follow the instructions in the [README ](https://github.com/meta-llama/llama3/blob/main/README.md)to run the download.sh scripts. When the script asks for your unique custom URL, please copy and paste one of the following URLs. (Clicking on the URL itself does not access the model):
Meta Llama 3:
[Meta Llama 3 repository](https://www.github.com/meta-llama/llama3)
[README](https://github.com/meta-llama/llama3/blob/main/README.md)
[download.sh](https://github.com/meta-llama/llama3/blob/main/download.sh)
URL
https://download6.llamameta.net*********************************311

### Output
````Downloading 8b_pre_trained
seq: unrecognized option: f
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: seq [-w] [-s SEP] [FIRST [INC]] LAST

Print numbers from FIRST to LAST, in steps of INC.
FIRST, INC default to 1.

        -w      Pad to last with leading zeros
        -s SEP  String separator
Connecting to download6.llamameta.net (18.161.111.26:443)
params.json          100% |************************************************************************|   211  0:00:00 ETA
Connecting to download6.llamameta.net (18.161.111.26:443)
tokenizer.model      100% |************************************************************************| 2132k  0:00:00 ETA
Connecting to download6.llamameta.net (18.161.111.26:443)
checklist.chk        100% |************************************************************************|   150  0:00:00 ETA
Checking checksums
md5sum: can't open 'consolidated.00.pth': No such file or directory
consolidated.00.pth: FAILED
params.json: OK
tokenizer.model: OK
md5sum: WARNING: 1 of 3 computed checksums did NOT match````

## Runtime Environment
- Model: [eg: `meta-llama-3-8b`]
- Using via huggingface?: [no]
- OS: [Windows]
- GPU VRAM: RTX 3050 4GB (Laptop) 
- Number of GPUs: 1
- GPU Make: [Nvidia]

**Comment by mreso** [comment]
Hi @Arwindhraj seems like seq in powershell does not support the -f parameter. To get you unblocked you can locally change your download.sh file by replacing [lined 45:48](https://github.com/meta-llama/llama3/blob/14aab0428d3ec3a9596f1dea06d9c564f9c0e35f/download.sh#L45C5-L48C9) against this:
```
for s in $(seq 0 ${SHARD})
    do
        wget --continue ${PRESIGNED_URL/'*'/"${MODEL_PATH}/consolidated.0${s}.pth"} -O ${TARGET_FOLDER}"/${MODEL_FOLDER_PATH}/consolidated.0${s}.pth"
    done
```

**Comment by Arwindhraj** [comment]
Hello @mreso , now the 8b_pre_trained model is downloading. Thank you so much for your help!
