### ISSUE TITLE
Even after eot_it Llama3 Intruct 8B keep talking to it self until reaching new_max_tokens...

### ISSUE THREAD

**Issue by feki-younes** [meta-llama/llama3#224]
Hi !
Thank you for these updates. For my case, I updated the tokenizer config as mentioned but always getting multiple lines with the same output (the first answer from the assistant but after it loops on the input system prompt until having the generated new_max_tokens .)
Many informations and different ones ! I'm a bit lost, do you have a clear code example to see if I'm wrongly using the model please ?
Regards

Here is my code :

```python
messages = [
{"role": "system", "content": "You are the best chatbot and your name is ESG-IGL"},
{"role": "user", "content": "Who are you?"},
]

input_ids = tokenizer.apply_chat_template(
messages,
add_generation_prompt=True,
return_tensors="pt"
).to(model.device)

terminators = [
tokenizer.eos_token_id,
tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = model.generate(
input_ids,
max_new_tokens=64,
eos_token_id=terminators,
do_sample=False,
)
response = outputs[0][input_ids.shape[-1]:]
print(tokenizer.decode(response, skip_special_tokens=True))

# Note : even when I set skip_special_tokens to False, the Output is the same.

```

### Output
 ```
What is your name?ESG-IGL.…

You are the best chatbot and your name is ESG-IGL.…

You are the best chatbot and your name is ESG-IGL.…

You are the best chatbot and your name is ESG-IGL.…

You are the best chat
```

## Runtime Environment
- Model: meta-llama-3-8b-instruct
- Using via huggingface?: no
- OS:  Windows
- GPU VRAM: 48 GO Nvidia A6000
- Number of GPUs: 1 
- GPU Make: Nvidia

**Comment by fbnav** [comment]
Hi, it looks like you are using huggingface to run the model. I was not able to reproduce this issue, could you provide the entrie script? Could you also try using the model with Transformers pipeline and see if you get a similar result?

For reference, you can also check out how to [run our model using HF on our Getting Started Guide](https://llama.meta.com/docs/llama-everywhere/running-meta-llama-on-windows/).

We also have an [example notebook](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/Running_Llama3_Anywhere/Running_Llama_on_HF_transformers.ipynb) on our Llama-recipes Github Repo that you could refer to that showcases how to use already converted weights as well as converting them yourself.

**Comment by feki-younes** [comment]
I downloaded the files config json config from huggingface using the available Meta-Llama repo ! I saved all the files under llama-3-Instruct folder.
This is the test using the pipiline method code ! I got the same output.
By the way, I tested the available shared method  "" [un our model using HF on our Getting Started Guide](https://llama.meta.com/docs/llama-everywhere/running-meta-llama-on-windows/). "" but the output is the question copied N times ...

This is the code : 
```
model_id = "./llama-3-Instruct/"
pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16},
    device_map="auto",
)

messages = [
{"role": "system", "content": "You are the best chatbot and your name is ESG-IGL"},
{"role": "user", "content": "Who are you?"},
]

prompt = pipeline.tokenizer.apply_chat_template(
        messages, 
        tokenize=False, 
        add_generation_prompt=True
)

terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = pipeline(
    prompt,
    max_new_tokens=64,
    eos_token_id=terminators,
    do_sample=False,
    #temperature=0.000001,
    #top_p=1,
)
print(outputs[0]["generated_text"][len(prompt):])
```

**Comment by fbnav** [comment]
Thank you for providing more information. Are you using already converted HF weights or the original weights?

To use already converted weights, you can try updating the model name to `model_id = "meta-llama/Meta-Llama-3-8B-Instruct"` and re-try. Setting the model id to this will use the HF converted Meta-Llama-3-8B-Instruct model to run this example. Delete/re-name any folder you may have created and called `meta-llama` in this directory before running.

Instead, if you downloaded the original weights and saved them in your `llama-3-Instruct` folder, you'll need to convert them to HF format using the `convert_llama_weights_to_hf.py` script and update `model_id` to point to the path of the converted weights. You can find steps to do this in our [example notebook](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/Running_Llama3_Anywhere/Running_Llama_on_HF_transformers.ipynb).

**Comment by feki-younes** [comment]
Well thank you very much for this help ! I think the worse idea was to take all config from HF.
The model is stopping generation now. Thank you ! 🥇
