### ISSUE TITLE
Llama3 gets it wrong on simple data analysis and math

### ISSUE THREAD

**Issue by mzeesam** [meta-llama/llama3#233]
I installed Ollama and pulled llama3 model 8B (4.7GB). 
I then ran a simple prompt by asking the model to analyze json data with 10 bank transaction records. The model got it wrong in terms of summation of the withdrawals and deposits. What could be wrong?

Below is a screenshot:
![image](https://github.com/meta-llama/llama3/assets/31076800/9ff9986e-7d95-4c4c-83e9-6a4aa3665595)

Runtime Environment
- Model: meta-llama-3-8b
- OS: Windows server 2022
- Virtual Machine

**Additional context**
Add any other context about the problem or environment here.

**Comment by subramen** [comment]
Generally LLMs including Llama are not precise on numerical data and arithmetic, and so any numerical analysis is susceptible to hallucinations.

**Comment by mzeesam** [comment]
Thank you.
