### ISSUE TITLE
[question] Do tokens which occur more commonly have lower token_ids?

### ISSUE THREAD

**Issue by spookyQubit** [meta-llama/llama3#236]
Was wondering if the token_ids in llama3's tokenizer sorted such that tokens which occur more frequently (according to the statistics of the data on which the tokenizer was trained) have lower token_id?

Just as an example, lets see the token_ids for the words "are" and "ARE". If the hypothesis is true that more frequent tokens have lower token_id, then we would expect "are" to have a lower token_id that "ARE". And indeed that is the case:
```python
>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained('meta-llama/Meta-Llama-3-8B-Instruct')

>>> tokenizer.convert_tokens_to_ids('are')
548

>>> tokenizer.convert_tokens_to_ids('ARE')
4577
```

I am trying to implement something which requires me to know the occurrence rank of tokens. If I know the answer to the above question, I might use token_id as a proxy for inverse rank. 

Thanks.

**Comment by albertodepaola** [comment]
Hi @spookyQubit, thanks for you question!

Based on how [BPE tokenizer](https://huggingface.co/docs/transformers/tokenizer_summary#byte-pair-encoding-bpe) work, that would be the case. Still, depending on what you are trying to implement, it's important to note that special tokens and out of vocabulary tokens don't follow this rule and there might be additional edge cases you would need to consider.

Thanks,

**Comment by spookyQubit** [comment]
Thanks @albertodepaola . Appreciate your quick response.
