### ISSUE TITLE
Llama3 Model loading checkpoint failed

### ISSUE THREAD

**Issue by drnirajindia** [meta-llama/llama3#248]
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_name = "E:\\Niraj_Work\\LLM_Models\\Meta-Llama-3-8B-Instruct\\"  #our offline model is stored at this location
tokenizer =  AutoTokenizer.from_pretrained(model_name, return_tensors='pt')
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
tokenizer.pad_token = tokenizer.eos_token

After running gives the following error...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Process finished with exit code -1073741819 (0xC0000005)

**Comment by subramen** [comment]
Cannot tell what the issue is without more details. Closing this now, please open a new issue following the provided issue template including information about your runtime platform.

**Comment by eccstartup** [comment]
How was it solved? @drnirajindia
