### ISSUE TITLE
Is there a problem with the generation code?

### ISSUE THREAD

**Issue by ZeroAGI** [meta-llama/llama3#258]
https://github.com/meta-llama/llama3/blob/d3eca219e453eca77ce1e180f48954c7d67467a9/llama/generation.py#L180

there is

```
logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
```

But, shouldn’t it be like this? Because the next token needs to be generated based on all the historical tokens.

```
logits = self.model.forward(tokens[:, 0:cur_pos], 0)
```

**Comment by mreso** [comment]
Hi @ZeroAGI historical tokens are represented by the kv cache state, see: https://github.com/meta-llama/llama3/blob/d3eca219e453eca77ce1e180f48954c7d67467a9/llama/model.py#L168

**Comment by ZeroAGI** [comment]
> Hi @ZeroAGI historical tokens are represented by the kv cache state, see:
> 
> https://github.com/meta-llama/llama3/blob/d3eca219e453eca77ce1e180f48954c7d67467a9/llama/model.py#L168

Hi @mreso , thanks for your reply.

If I am not using cache, can I simply do this?

```
keys = xk
values = xv
```

Thanks

**Comment by mreso** [comment]
Not sure why you would want to deactivate kv caching. It is a technique to accelerate token generation in transformer models. A great explanation of this technique can e.g. be found in this blog post https://www.dipkumar.dev/becoming-the-unbeatable/posts/gpt-kvcache/
