### ISSUE TITLE
model is getting loaded unevenly

### ISSUE THREAD

**Issue by abpani** [meta-llama/llama3#268]
Hello I am finetuning Llama 3 8b with peft and qlora.
My model is getting loaded like this with batch size of 1. 
I can't even do batch size more than 1 it cause OOM.
![Screenshot 2024-07-08 at 7 31 22 PM](https://github.com/meta-llama/llama3/assets/164398496/31e59e6d-8054-4c30-8d22-d0d9cdb18272)
Please help.  Tried with multiple pytorch and flash attn versions.
Torch 2.3.0
flash attn 2.5.9

**Comment by mreso** [comment]
@abpani What peft/qlora implementation are you using? I would suggest asking in the library specific repo/forum instead. We do not provide a peft/qlora implementation in this repo. Feel free to reopen if there are further questions.

**Comment by abpani** [comment]
No this happens with just Automodelforcasuallm loading.
even before processing peft.

**Comment by mreso** [comment]
Hi @abpani AutoModel is a huggingface/transformers class. The transformer implementation in this repo is separate from it. You will most likely find help here: https://discuss.huggingface.co
