### ISSUE TITLE
Error downloading model Meta-Llama-3.1-8B using this repo!

### ISSUE THREAD

**Issue by numoh** [meta-llama/llama3#278]
I'm getting 403 error when I clone this repo to download model Meta-Llama-3.1-8B. Which repo should I use?

I can download model Meta-Llama-3-8B with this repo otherwise.

**Comment by Quasimondo** [comment]
I was able to download them from the llama-models repo (after also getting an error when trying the download.sh from llama3):
https://github.com/meta-llama/llama-models/tree/main/models/llama3_1

**Comment by numoh** [comment]
> I was able to download them from the llama-models repo (after also getting an error when trying the download.sh from llama3):
> 
> https://github.com/meta-llama/llama-models/tree/main/models/llama3_1

I will try that, thanks 😃

**Comment by numoh** [comment]
> I was able to download them from the llama-models repo (after also getting an error when trying the download.sh from llama3): https://github.com/meta-llama/llama-models/tree/main/models/llama3_1

It did not work :(
