### ISSUE TITLE
how to download and use Meta-Llama-3.1-8B ? Prompt 403 error

### ISSUE THREAD

**Issue by Juvarunst** [meta-llama/llama3#288]
I am already there "https://llama.meta.com/llama-downloads" I applied for a unique custom URL, but the third download still prompted "403: Forbidden". Why? Has anyone encountered the same problem before?
![err3](https://github.com/user-attachments/assets/4a03573b-e3d9-4f32-9b3f-e51d15fba538)
![err4](https://github.com/user-attachments/assets/fed1ff5d-7bc6-40d6-8831-55e5e1f2dd8e)

**Comment by Juvarunst** [comment]
> @Juvarunst can you give try one more time with new URL and provide the request id?

Request ID: 1710880222981693
But problems still exist.

![777](https://github.com/user-attachments/assets/d93cca58-46de-4e7d-9c52-e002cba52b6a)

DESKTOP-021DSF0@DESKTOP-K155IV6 MINGW64 /e/llama3 (main)
$ ./download.sh
Enter the URL from email: https://llama3-1.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicGE1b285cWtuaHh5cDJobzU1N3owanI1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk4MDEzN319fV19&Signature=PKCNtwULIKJS-YeZJSdYH5NsoSQAKw7Ra%7E3IAn%7E4CwQhxrfdn5mXdnPx6wRrtLEFKoIhdOyFCRf9-y98xJAKzh1kdCgBLiPEqms3Y3DNabH8CZaf7Hkk0q5tl3zARXhr17hpaks-%7E8CM7IZbhVV67B-E9k9iswneClJY6lACG4FkNO%7EzBrSGSJW-ENoLHyVtmDJS%7Eoan9Gk2UGGx9UV7xF0jmz3lKiD%7ERRwB7hDJd9K3T4EgKqhe0jzXur2hT7myqfFpXBtOUpS4rI5e6FVpNeJYB3vdeR2yC4bOdeLChsevQqKW5gsqu8FGKmPcaqHEniOrMhGM6RoKk-ZJxoeItQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=391358116864261

Enter the list of models to download without spaces (8B,8B-instruct,70B,70B-instruct), or press Enter for all: 8B
Downloading LICENSE and Acceptable Usage Policy
--2024-07-25 16:00:06--  https://llama3-1.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicGE1b285cWtuaHh5cDJobzU1N3owanI1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk4MDEzN319fV19&Signature=PKCNtwULIKJS-YeZJSdYH5NsoSQAKw7Ra~3IAn~4CwQhxrfdn5mXdnPx6wRrtLEFKoIhdOyFCRf9-y98xJAKzh1kdCgBLiPEqms3Y3DNabH8CZaf7Hkk0q5tl3zARXhr17hpaks-~8CM7IZbhVV67B-E9k9iswneClJY6lACG4FkNO~zBrSGSJW-ENoLHyVtmDJS~oan9Gk2UGGx9UV7xF0jmz3lKiD~RRwB7hDJd9K3T4EgKqhe0jzXur2hT7myqfFpXBtOUpS4rI5e6FVpNeJYB3vdeR2yC4bOdeLChsevQqKW5gsqu8FGKmPcaqHEniOrMhGM6RoKk-ZJxoeItQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=391358116864261
Resolving llama3-1.llamameta.net (llama3-1.llamameta.net)... 13.33.183.15, 13.33.183.99, 13.33.183.66, ...
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|13.33.183.15|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-25 16:00:08 ERROR 403: Forbidden.

--2024-07-25 16:00:08--  https://llama3-1.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicGE1b285cWtuaHh5cDJobzU1N3owanI1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk4MDEzN319fV19&Signature=PKCNtwULIKJS-YeZJSdYH5NsoSQAKw7Ra%7E3IAn%7E4CwQhxrfdn5mXdnPx6wRrtLEFKoIhdOyFCRf9-y98xJAKzh1kdCgBLiPEqms3Y3DNabH8CZaf7Hkk0q5tl3zARXhr17hpaks-%7E8CM7IZbhVV67B-E9k9iswneClJY6lACG4FkNO%7EzBrSGSJW-ENoLHyVtmDJS%7Eoan9Gk2UGGx9UV7xF0jmz3lKiD%7ERRwB7hDJd9K3T4EgKqhe0jzXur2hT7myqfFpXBtOUpS4rI5e6FVpNeJYB3vdeR2yC4bOdeLChsevQqKW5gsqu8FGKmPcaqHEniOrMhGM6RoKk-ZJxoeItQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=391358116864261
Reusing existing connection to llama3-1.llamameta.net:443.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-25 16:00:08 ERROR 403: Forbidden.


DESKTOP-021DSF0@DESKTOP-K155IV6 MINGW64 /e/llama3 (main)
$

**Comment by Juvarunst** [comment]
> @Juvarunst can you give try one more time with new URL and provide the request id?

![Download Llama](https://github.com/user-attachments/assets/1f9083a4-0857-43ce-8856-29ed1075d4db)

**Comment by zhonghe0615** [comment]
same issue here

**Comment by AnttiMJohansson** [comment]
Same issue.

**Comment by damonChenzf07** [comment]
> ## Same issue.
> I resolved this. It was my error as I has cloned llama3. This is also clear from the prompt that offers llama3 models.
> 
> So, resolution is to clone the correct repo that is meta-lama/llama-models, then run the donwnload.sh from the llama3_1 folder. Download with url key worked perfectly.

I follwed as your steps, but still failed!!

damon@Zdrive:~/Llama$ git clone https://github.com/meta-llama/llama-models.git
Cloning into 'llama-models'...
remote: Enumerating objects: 162, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 162 (delta 47), reused 38 (delta 33), pack-reused 90
Receiving objects: 100% (162/162), 1.31 MiB | 2.47 MiB/s, done.
Resolving deltas: 100% (73/73), done.
damon@Zdrive:~/Llama$ cd llama-models/
damon@Zdrive:~/Llama/llama-models$ ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  docs  Llama_Repo.jpeg  MANIFEST.in  models  pyproject.toml  README.md  requirements.txt  setup.py
damon@Zdrive:~/Llama/llama-models$ cd models/
damon@Zdrive:~/Llama/llama-models/models$ ls
__init__.py  llama2  llama3  llama3_1
damon@Zdrive:~/Llama/llama-models/models$ cd llama3_1/
damon@Zdrive:~/Llama/llama-models/models/llama3_1$ ls
api  download.sh  eval_details.md  __init__.py  LICENSE  MODEL_CARD.md  README.md  requirements.txt  USE_POLICY.md
damon@Zdrive:~/Llama/llama-models/models/llama3_1$ bash download.sh 
Enter the URL from email: https://llama3-1.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiYWowanVqenl6NGc2aXBneTN4anU0cG4zIiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMjMwNjQ1OH19fV19&Signature=gulee0lrq5MDLIN37fJxWh1vNshrZnG%7E0T7uYc-h3LyWfiJ56RXrfrOYfj3uq4xGJgfk35cvkQ9T5ljNsT435dRriF4rg4XOq-PJjTnHu6aEzYYgaJ49o6c9f8CjcGdf3yrtfDyY4Uy91h78H2fzhbwFuZSRtViTtgDP67KiMYmvg0-EHyS-j0FQwFx13ZgK2LucfhdQplBctldfVEikfVY9dIaiOUGbdzx-lHtkhOnA-G1mZe4Eh3DdF6hOANaPgXlIw1IONPlTMhhFMP3Y1SmlVHaxMA7XbNhP5GUsnWBs%7ELP1rBWoWr0Y%7E-j3FOLo%7EwFdH55IErzrxYHYN7IDFQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=491229826788968

 **** Model list ***
 -  meta-llama-3.1-405b
 -  meta-llama-3.1-70b
 -  meta-llama-3.1-8b
 -  meta-llama-guard-3-8b
 -  prompt-guard
Choose the model to download: meta-llama-3.1-8b

 Selected model: meta-llama-3.1-8b 

 **** Available models to download: ***
 -  meta-llama-3.1-8b-instruct
 -  meta-llama-3.1-8b
Enter the list of models to download without spaces or press Enter for all: 
Downloading LICENSE and Acceptable Usage Policy
--2024-07-29 11:00:01--  https://llama3-1.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiYWowanVqenl6NGc2aXBneTN4anU0cG4zIiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMjMwNjQ1OH19fV19&Signature=gulee0lrq5MDLIN37fJxWh1vNshrZnG%7E0T7uYc-h3LyWfiJ56RXrfrOYfj3uq4xGJgfk35cvkQ9T5ljNsT435dRriF4rg4XOq-PJjTnHu6aEzYYgaJ49o6c9f8CjcGdf3yrtfDyY4Uy91h78H2fzhbwFuZSRtViTtgDP67KiMYmvg0-EHyS-j0FQwFx13ZgK2LucfhdQplBctldfVEikfVY9dIaiOUGbdzx-lHtkhOnA-G1mZe4Eh3DdF6hOANaPgXlIw1IONPlTMhhFMP3Y1SmlVHaxMA7XbNhP5GUsnWBs%7ELP1rBWoWr0Y%7E-j3FOLo%7EwFdH55IErzrxYHYN7IDFQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=491229826788968
Resolving llama3-1.llamameta.net (llama3-1.llamameta.net)... 108.138.246.122, 108.138.246.20, 108.138.246.81, ...
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|108.138.246.122|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-29 11:00:02 ERROR 403: Forbidden.

damon@Zdrive:~/Llama/llama-models/models/llama3_1$

**Comment by Piotr-rogal** [comment]
I use this method and it works.

1. Go to your llama folder (e.g. cd llama3)
2. List files (ls)
3. Remove download.sh (rm download.sh)
4. Go to https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/download.sh
5. Copy data from download.sh (copy raw file)
6. Use nano to create download.sh (nano download.sh)
7. Paste data from memory (ctrl+v)
8. End nano and write to file (ctrl+x)
9. Add permision to download.sh (chmod +x download.sh)
10. Run download.sh (./download.sh)

Rest the same as before - paste link from meta email

**Comment by Max-Headspace** [comment]
> 

are you on wsl or what?
i had to run WSL2:
- 
sudo apt update
sudo apt install --reinstall net-tools

-
sudo apt install net-tools

and in windows i ran:
-
netsh winsock reset

then restart pc

***back in WSL2
-
wsl
ip addr

-
sudo rm /etc/resolv.conf
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "nameserver 8.8.4.4" >> /etc/resolv.conf'

-
sudo nano /etc/wsl.conf

#Add the following lines to prevent auto-generation of resolv.conf:
[network]
generateResolvConf = false


#then type the foloowing
ctrl+x 
#it will say something like do you want to save before exiting and type y for yes n for no
-
y #hit enter
#you should be done but test
-
wsl --shutdown
wsl
-
ping 8.8.8.8

-
ping google.com

-
at least that resolved my issue... i tried to update like sudo apt update and it was not downloading anything from the jammy jank. so i was like what the deuce?!

**Comment by rasibweb** [comment]
I'm getting this error. 

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Scripts\llama.exe\__main__.py", line 7, in <module>
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\llama.py", line 44, in main
    parser.run(args)
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\llama.py", line 38, in run
    args.func(args)
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 174, in run_download_cmd
    _meta_download(model, meta_url)
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 143, in _meta_download
    asyncio.run(downloader.download())
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 263, in download
    await self.get_file_info(client)
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_toolchain\cli\download.py", line 252, in get_file_info
    response.raise_for_status()
  File "C:\Users\HP745\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://llama3-2-lightweight.llamameta.net/Llama-3.2-11B-Vision/checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiOHpyZTAybGJkeGN1b3c0ZXJkbjV1Nm9lIiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTItbGlnaHR3ZWlnaHQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyNzYyMTQwN319fV19&Signature=kOgwGctTEHUF-s5HLCn6WEI7xLwOI5e%7E6Z2AUxj8fgKgjrL63dGG3Wn5IqI6vbqoik4s54QQaZj0J0utJ2oOsWB1-bEOVItsDn-LXBZnLF9Q4f9FainhOaQ16324sLmnsJKOgprAVY2l9j5WdhNMFMmjj9-IB5l9hbvAviTeHNJOpzPV7av-ZEGFcvc2Dnn909G%7ErjFKLXuU0GdC-xAeOkBVHh3fzYKIQBV6FW-Roi8H87-2cCOF8XHRlVPsDhuloADvi5pssdqP8qngtdznVZcx-J8ivkXCFkWUm%7Ek04qEvltW71rxXw%7EYX63d2B6gs1oXA9zcCv4t3JPDZMJrUwQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1947422042337763'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403`

**Comment by rasibweb** [comment]
Got it. Thanks 😊

**Comment by Wang-Ying-Yi** [comment]
> I use this method and it works.
> 
> 1. Go to your llama folder (e.g. cd llama3)
> 2. List files (ls)
> 3. Remove download.sh (rm download.sh)
> 4. Go to https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/download.sh
> 5. Copy data from download.sh (copy raw file)
> 6. Use nano to create download.sh (nano download.sh)
> 7. Paste data from memory (ctrl+v)
> 8. End nano and write to file (ctrl+x)
> 9. Add permision to download.sh (chmod +x download.sh)
> 10. Run download.sh (./download.sh)
> 
> Rest the same as before - paste link from meta email and next choice model:
> 
> **** Model list ***
> 
> ```
> meta-llama-3.1-405b
> meta-llama-3.1-70b
> meta-llama-3.1-8b
> meta-llama-guard-3-8b
> prompt-guard
> Choose the model to download: meta-llama-3.1-8b
> ```
> 
> Selected model: meta-llama-3.1-8b
> 
> **** Available models to download: ***
> 
> ```
> meta-llama-3.1-8b-instruct
> meta-llama-3.1-8b
> ```

I tried this way it still shows the same error 403 Forbidden
