### ISSUE TITLE
May I kindly request to cite our paper in "The Llama 3 Herd of Models" ?

### ISSUE THREAD

**Issue by wyt2000** [meta-llama/llama3#296]
Dear develops,

I hope this issue finds you well. My name is Yutong Wu, a PhD student at the Institute of Computing Technology, Chinese Academy of Sciences. I recently had the opportunity to read the insightful paper of llama3 titled "The Llama 3 Herd of Models", and I was impressed by the contribution it makes in synthetic data generation for coding task in 4.3.1.

However, I noticed that our previously work "InverseCoder: Unleashing the Power of Instruction-Tuned Code LLMs with Inverse-Instruct" was not cited. Our paper addresses several key aspects that are closely related to the synthetic data generation method used in llama3, and I believe that including a citation to our work would provide a more comprehensive background and acknowledge the contributions made in this domain.

Specifically, our paper also utilizes the idea of backtranslation to expand the SFT dataset for programming task. Our method Inverse-Instruct focuses on the misalignment between translation of formal and informal languages: translating formal language (i.e., code) to informal language(i.e., natural language) is more straightforward than the reverse, while llama3 uses backtranslation to generate code from comments and docstrings. It is interesting to compare the performance difference between the two synthetic directions.

For your reference, here is the complete citation of our paper:

```
@misc{wu2024inversecoderunleashingpowerinstructiontuned,
      title={InverseCoder: Unleashing the Power of Instruction-Tuned Code LLMs with Inverse-Instruct}, 
      author={Yutong Wu and Di Huang and Wenxuan Shi and Wei Wang and Lingzhe Gao and Shihao Liu and Ziyuan Nan and Kaizhao Yuan and Rui Zhang and Xishan Zhang and Zidong Du and Qi Guo and Yewen Pu and Dawei Yin and Xing Hu and Yunji Chen},
      year={2024},
      eprint={2407.05700},
      archivePrefix={arXiv},
      primaryClass={cs.CL},
      url={https://arxiv.org/abs/2407.05700}, 
}
```

I kindly request you consider adding this citation in your future versions or related publications. Your cooperation in this matter is highly appreciated.
Thank you for your attention to this request. I look forward to any future collaboration opportunities.

Best regards,
Yutong Wu.

**Comment by jspisak** [comment]
Thank you for reaching out - I will let the main paper authors know for future updates.
