### ISSUE TITLE
When do we get access on HF? i NEED IT

### ISSUE THREAD

**Issue by samedovzaur1** [meta-llama/llama3#32]

**Comment by iboyles** [comment]
It took me less than an hour to get access on huggingface after sending the thing, when I went to their website it gave me access immediately hope this helps.

**Comment by mertbozkir** [comment]
Same for me, maybe 15 minutes

**Comment by jspisak** [comment]
cc @osanseviero #kingllama

**Comment by samedovzaur1** [comment]
> It took me less than an hour to get access on huggingface after sending the thing, when I went to their website it gave me access immediately to the repo version of the model, hope this helps.

Thank you for the replay ibo :D. that was an excitement i got couple of minutes later

**Comment by osanseviero** [comment]
Enjoy these llamastic times! 🦙 🦙 🦙 🎉
