### ISSUE TITLE
[Question about llama3 paper] Is the context parallel independent to dp, pp and tp?

### ISSUE THREAD

**Issue by kisseternity** [meta-llama/llama3#324]
In the paper _The Llama 3 Herd of Models_, I've noticed the scaling configurations for llama3 405B pretraining for 16384 gpu4 be set to tp=8, cp=16, pp=16, dp=4 for seq len 131072. As far as I know, the gpu nums should be the product of tp, cp, pp, dp which should be 8192 gpus. Did I get something wrong? Please take a look, thanks.

FYI, the configurations in the paper is as follows:
 
![image](https://github.com/user-attachments/assets/b087d669-ef09-454e-bb94-3eac3ec3c9e3)

**Comment by jianyuh** [comment]
Hi @kisseternity , this should be a typo. DP should be 8, so we have TP * CP * PP * DP=16384, and DP * Batch size/DP * Seq.Len. = 16M. Ask internally to submit a fix for next arxiv paper update.

**Comment by kisseternity** [comment]
> Hi @kisseternity , this should be a typo. DP should be 8, so we have TP * CP * PP * DP=16384, and DP * Batch size/DP * Seq.Len. = 16M. Ask internally to submit a fix for next arxiv paper update.

Thanks for your reply, that makes sense.
