### ISSUE TITLE
Some files missing in the downloaded Llama3.2-1B-instruct model.

### ISSUE THREAD

**Issue by vedanshthakkar** [meta-llama/llama3#344]
I downloaded the Llama3.2-1B-instruct model from here: https://www.llama.com/llama-downloads/

In the downloaded folder, some files like config.json and others (which are required during inference/finetuning) are missing. Here are the files which gets downloaded:

![image](https://github.com/user-attachments/assets/4d8e5f62-2148-45c1-949e-bdb017ed68c9)

When making an inference using hugging face code (https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct), I get this error:

`llama_models/Llama3.2-1B-Instruct does not appear to have a file named config.json. `

When I added config.json from previously downloaded llama model (llama3-8B-Instruct), I get the following error:

`OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /llama_models/Llama3.2-1B-Instruct. 
`
I am wondering why the other files are not there in the downloaded model folder?

**Comment by vedanshthakkar** [comment]
Is anyone else facing this issue?

**Comment by salmanjabbarkhan** [comment]
same problem here! It's missing the important files like pytorch_model.bin What to do now?

**Comment by pcuenca** [comment]
Hello @vedanshthakkar! It looks like you downloaded the original Llama 3.2 checkpoints, which are suitable for use in codebases such as [llama-stack](https://github.com/meta-llama/llama-stack) or [llama-models](https://github.com/meta-llama/llama-models).

If you want to use the transformers APIs, you need to use the checkpoints in transformers format. Note that you don't have to download them first, the following will automatically download and cache Llama 3.2 1B for subsequent use:

```python
import torch
from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model= "meta-llama/Llama-3.2-1B-Instruct",
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
```

If you do want to download them locally, I'd recommend you use the Hugging Face Hub CLI tool like this:

```bash
pip install huggingface-hub
huggingface-cli download --local-dir Llama-3.2-1B-Instruct meta-llama/Llama-3.2-1B-Instruct  --exclude "original/*"
```

The command above will download the transformers checkpoint to a local directory called `Llama-3.2-1B-Instruct`.

**Comment by vedanshthakkar** [comment]
@pcuenca 

Downloading from Hugging Face Hub CLI worked! Thanks.
