### ISSUE TITLE
Cannot download `llama model download: error: Model Llama-3.2-11B-Vision-Instruct not found`

### ISSUE THREAD

**Issue by Travis-Barton** [meta-llama/llama3#350]
I made a clean 3.10 conda env on windows 11.

I have llama-stack installed. I run 

```
 llama model download --source meta --model-id Llama-3.2-11B-Vision-Instruct --meta-url "https://llama3-2-multimodal.llamameta.net/*?Policy=<my-code>"
```

I have an email saying that my code is valid (attached) and yet I still get this error:
```
usage: llama model download [-h] [--source {meta,huggingface}] [--model-id MODEL_ID] [--hf-token HF_TOKEN] [--meta-url META_URL] [--ignore-patterns IGNORE_PATTERNS] [--manifest-file MANIFEST_FILE]
llama model download: error: Model meta-llama/Llama-3.2-11B-Vision-Instruct not found
```

This same thing applies to other models as well.

![image](https://github.com/user-attachments/assets/85592d9c-20e0-4a20-aa6f-d9236d0ff215)

**Comment by ashwinb** [comment]
![image](https://github.com/user-attachments/assets/0623ccaa-88be-457e-94b8-0b47308828a9)

you need to use `Llama3.2-11B-Vision-Instruct` as the model-id

**Comment by Travis-Barton** [comment]
Same effect with that new name too /:

**Comment by Travis-Barton** [comment]
Resolved! 

`Llama-3.2` should be `Llama3.2` Thanks again @ashwinb!!
