### ISSUE TITLE
Inconsistent Responses: Conflicting Acknowledgments Based on User Messages

### ISSUE THREAD

**Issue by sherinnishara** [meta-llama/llama3#364]
While interacting with the Meta AI chatbot, it initially agreed to a request, stating, "I can do that." Later in the conversation, it contradicted this by explaining that it only responds based on user messages and cannot fulfill the request as initially stated.

**Comment by adi-ydv-1** [comment]
@sherinnishara what was the input text ??

**Comment by adi-ydv-1** [comment]
@sherinnishara  @lov37ess  both of you together opened this issue ??

**Comment by adi-ydv-1** [comment]
> > @sherinnishara  @lov37ess  both of you together opened this issue ??
> 
> Now the exception was handled like this
> 
> ![Screenshot_20241212_171139_WhatsApp.jpg](https://private-user-images.githubusercontent.com/147413289/395152758-2f6c1b1a-5b5e-4994-b331-96ec02a2f317.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzkxNzEsIm5iZiI6MTczNDE3ODg3MSwicGF0aCI6Ii8xNDc0MTMyODkvMzk1MTUyNzU4LTJmNmMxYjFhLTViNWUtNDk5NC1iMzMxLTk2ZWMwMmEyZjMxNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxMjIxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDYzNDkwMzBhNjY1ZTIzMTI4NzRlYTNlZDljM2YzYmQzNzk1YTZkMzdlYmJhMTAzOWM4MjI3MDcwMzFmODQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oAndC3HulDXuKVNg4KObhTwbIlixo0Jpuprsis-TbtU)
> 
> Input : If you don't have any memory, how did you agree to my [task]?

I think what chatbot means is it interact with you like a human but everytime you have to remind the bot related to what you are asking question...
