### ISSUE TITLE
The README link in the "Get started with Meta Llama 3" sends you to Llama2 README

### ISSUE THREAD

**Issue by evdcush** [meta-llama/llama3#41]
The "Get started with Meta Llama 3" email sent after agreeing to the license for model download points the user to two links:

- https://github.com/meta-llama/llama3
- https://github.com/meta-llama/llama/blob/main/README.md

> Visit [**the Llama repository**](https://github.com/meta-llama/llama3) for the model on GitHub and follow the instructions in the [**README**](https://github.com/meta-llama/llama/blob/main/README.md) to run the download.sh script. When the script asks for your unique custom URL, please copy and paste the following URL. (Clicking on the URL itself does not access the model):

The repository link is correctly directing users to this llama3 repo, but the README link sends users to the Llama 2 (llama) README.

Should the user navigate from the README, they may go for the the `download.sh` script for llama2.

**Comment by jspisak** [comment]
working on this - great catch!!

**Comment by jspisak** [comment]
fixed now - thanks again for raising it!
