### ISSUE TITLE
Meta-Llama-3-8B-Instruct does not appear to have a file named config.json

### ISSUE THREAD

**Issue by fzp0424** [meta-llama/llama3#54]
```
model_path = "/home/Meta-Llama-3-8B-Instruct"
self.tokenizer = AutoTokenizer.from_pretrained(model_path)
self.model = AutoModelForCausalLM.from_pretrained(model_path, device_map = 'auto', torch_dtype = 'auto', do_sample = True)
```
When I try to load Llama3 in this way, it reports the error like the title. And I find the model I downloaded only contains 4 files: checklist.chk, consolidated.00.pth, params.json, and tokenizer.model. Is this right?

`Transformers==4.37.0`

**Comment by Maydaytyh** [comment]
same question

**Comment by fangyinc** [comment]
If you use `transformers`, please download the model from [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct).

**Comment by fzp0424** [comment]
> If you use `transformers`, please download the model from [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct).

Thanks!
