### ISSUE TITLE
convert_llama_weights_to_hf 

### ISSUE THREAD

**Issue by JosephChenHub** [meta-llama/llama3#58]
is there a script to convert weights to hf format?

**Comment by rupeshs** [comment]
@JosephChenHub  Are you looking for this https://huggingface.co/meta-llama/Meta-Llama-3-8B

**Comment by bkhanal-11** [comment]
@JosephChenHub you can use the script [convert_llama_weights_to_hf.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py). Also some instructions from llama-recipe:

```bash
## Install Hugging Face Transformers from source
pip freeze | grep transformers ## verify it is version 4.31.0 or higher

git clone git@github.com:huggingface/transformers.git
cd transformers
pip install protobuf
python src/transformers/models/llama/convert_llama_weights_to_hf.py \
   --input_dir /path/to/downloaded/llama/weights --model_size 7B --output_dir /output/path

```

**Comment by ArthurZucker** [comment]
https://github.com/huggingface/transformers/pull/30334 will add the script and everything you need
