### ISSUE TITLE
how many pth files are you supposed to download?

### ISSUE THREAD

**Issue by sudipsudip001** [meta-llama/llama3#61]
I tried to download the 70B Model and the script has already download consolidated.00.pth and consolidated.01.pth pth files each of 16GB and is running again to download consolidated.02.pth. Should I stop or should the process continue?
![Screenshot 2024-04-19 115507](https://github.com/meta-llama/llama3/assets/71699219/03032164-0568-4f38-8ee7-a3609f9dffdb)

**Comment by ArthurZucker** [comment]
Let it be! You have 8 files in total like this see [here](https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct/tree/main/original)

**Comment by sudipsudip001** [comment]
Aiight. Thanks!
