### ISSUE TITLE
What is "original" folder used for?

### ISSUE THREAD

**Issue by tingxueronghua** [meta-llama/llama3#64]
Although the README.md mentioned the "original" folder, we still do not know what is used for and when should we download it manually.

**Comment by TikaToka** [comment]
huggingface reposity has original forder, which contains model for llama3 codebase.

**Comment by tingxueronghua** [comment]
> huggingface reposity has original forder, which contains model for llama3 codebase. Therefore, if you intend to use llama 3 codebase, you need to download original folder.

Thanks!
