### ISSUE TITLE
wget not found

### ISSUE THREAD

**Issue by dhyeypatel03** [meta-llama/llama3#68]

**Comment by pianistprogrammer** [comment]
https://stackoverflow.com/questions/33886917/how-to-install-wget-in-macos

if you're using mac, worked for me, get wget

**Comment by 0xBLAHAJ** [comment]
For Windows get the .exe from https://eternallybored.org/misc/wget/ and put it in a folder included in your PATH env. variable

**Comment by Olney1** [comment]
If on a Mac: 

1. Install Homebrew: https://brew.sh/

2. brew install wget
