### ISSUE TITLE
Meta-Llama-3-8B-Instruct does not appear to have a file named config.json

### ISSUE THREAD

**Issue by zengraoli** [meta-llama/llama3#69]
use code：
`
import transformers
import torch

model_id = "/home/zeng/llm/model/llama3/Meta-Llama-3-8B-Instruct"
pipeline = transformers.pipeline(
    "text-generation", model=model_id, model_kwargs={"torch_dtype": torch.bfloat16}, device_map="auto"
)
`

error：
OSError: /home/zeng/llm/model/llama3/Meta-Llama-3-8B-Instruct does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/zeng/llm/model/llama3/Meta-Llama-3-8B-Instruct/None' for available files.

is need download 8b base model？

**Comment by mirdulvultr** [comment]
I am getting the same error, did you get it resolved

**Comment by pcuenca** [comment]
Hi @zengraoli! The config.json file is there in the repo: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/tree/main

Perhaps your local download did not work properly? What happens if you use `meta-llama/Meta-Llama-3-8B-Instruct` as the model_id?

**Comment by mirdulvultr** [comment]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[4], line 6
      2 import torch
      4 model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
----> 6 pipeline = transformers.pipeline(
      7     "text-generation", model=model_id, model_kwargs={"torch_dtype": torch.bfloat16}, device_map="auto"
      8 )
     10 pipeline("Hey how are you doing today?")

File /usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py:816, in pipeline(task, model, config, tokenizer, feature_extractor, image_processor, framework, revision, use_fast, token, device, device_map, torch_dtype, trust_remote_code, model_kwargs, pipeline_class, **kwargs)
    813                 adapter_config = json.load(f)
    814                 model = adapter_config["base_model_name_or_path"]
--> 816     config = AutoConfig.from_pretrained(
    817         model, _from_pipeline=task, code_revision=code_revision, **hub_kwargs, **model_kwargs
    818     )
    819     hub_kwargs["_commit_hash"] = config._commit_hash
    821 custom_tasks = {}

File /usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py:928, in AutoConfig.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    925 trust_remote_code = kwargs.pop("trust_remote_code", None)
    926 code_revision = kwargs.pop("code_revision", None)
--> 928 config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    929 has_remote_code = "auto_map" in config_dict and "AutoConfig" in config_dict["auto_map"]
    930 has_local_code = "model_type" in config_dict and config_dict["model_type"] in CONFIG_MAPPING

File /usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:631, in PretrainedConfig.get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    629 original_kwargs = copy.deepcopy(kwargs)
    630 # Get config dict associated with the base config file
--> 631 config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
    632 if "_commit_hash" in config_dict:
    633     original_kwargs["_commit_hash"] = config_dict["_commit_hash"]

File /usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:686, in PretrainedConfig._get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    682 configuration_file = kwargs.pop("_configuration_file", CONFIG_NAME)
    684 try:
    685     # Load from local folder or from cache or download from model Hub and cache
--> 686     resolved_config_file = cached_file(
    687         pretrained_model_name_or_path,
    688         configuration_file,
    689         cache_dir=cache_dir,
    690         force_download=force_download,
    691         proxies=proxies,
    692         resume_download=resume_download,
    693         local_files_only=local_files_only,
    694         token=token,
    695         user_agent=user_agent,
    696         revision=revision,
    697         subfolder=subfolder,
    698         _commit_hash=commit_hash,
    699     )
    700     commit_hash = extract_commit_hash(resolved_config_file, commit_hash)
    701 except EnvironmentError:
    702     # Raise any environment error raise by `cached_file`. It will have a helpful error message adapted to
    703     # the original exception.

File /usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:369, in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    367 if not os.path.isfile(resolved_file):
    368     if _raise_exceptions_for_missing_entries:
--> 369         raise EnvironmentError(
    370             f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
    371             f"'[https://huggingface.co/](https://huggingface.co/%3C/span%3E%3Cspan) class="ansi-bold" style="color:rgb(175,95,135)">{path_or_repo_id}/tree/{revision}' for available files."
    372         )
    373     else:
    374         return None

OSError: meta-llama/Meta-Llama-3-8B-Instruct does not appear to have a file named config.json. Checkout 'https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/tree/None' for available files.


Here's the whole trace

**Comment by mirdulvultr** [comment]
I tried 8b it worked perfectly but not the instruct ??

**Comment by zengraoli** [comment]
> Hi @zengraoli! The config.json file is there in the repo: https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/tree/main
> 
> Perhaps your local download did not work properly? What happens if you use `meta-llama/Meta-Llama-3-8B-Instruct` as the model_id?

the model file in this path（download from email url），but there is a significant difference compared to the llama2 model fold.
`
(llama3) zeng@zeng-pc:~/llm/model/llama3/Meta-Llama-3-8B-Instruct$ ls
checklist.chk  consolidated.00.pth  params.json  tokenizer.model
`

**Comment by zengraoli** [comment]
> I tried 8b it worked perfectly but not the instruct ??

the same problem

**Comment by agoriwmt** [comment]
same problem here

**Comment by mangoo1** [comment]
Cloning the full repo from `https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct` could resolve this issue.

**Comment by zengraoli** [comment]
> Cloning the full repo from `https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct` could resolve this issue.

Your request to access this repo has been successfully submitted, and is pending a review from the repo's authors.

have a long time？

**Comment by mangoo1** [comment]
30 to 60 mins-------- Original message --------From: Zeng Raoli ***@***.***>Date: Sat, 20 Apr 2024, 10:11 pmTo: meta-llama/llama3 ***@***.***>Cc: Deven Chen ***@***.***>, Comment ***@***.***>Subject: Re: [meta-llama/llama3] Meta-Llama-3-8B-Instruct does not appear to have a file named config.json (Issue #69)

Cloning the full repo from https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct could resolve this issue.

Your request to access this repo has been successfully submitted, and is pending a review from the repo's authors.
have a long time？

**Comment by zengraoli** [comment]
> 30 to 60 mins, should be easy.

oh no，i use code ：
`
from transformers import AutoModel
access_token = "*********"
model = AutoModel.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct", token=access_token)
`

download model：
config.json
model.safetensors.index.json
model-00001-of-00004.safetensors
model-00002-of-00004.safetensors
model-00003-of-00004.safetensors
model-00004-of-00004.safetensors

seems like missing files：
generation_config.json
special_tokens_map.json
tokenizer.json
tokenizer_config.json

can you send me the remaining files to my email？
127881100@163.com

**Comment by zengraoli** [comment]
thank you guys.

`
import transformers
import torch
# model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
model_id = "/home/zeng/llm/model/Meta-Llama-3-8B-Instruct"

pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16},
    device="cuda",
)

messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]

prompt = pipeline.tokenizer.apply_chat_template(
        messages, 
        tokenize=False, 
        add_generation_prompt=True
)

terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = pipeline(
    prompt,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
print(outputs[0]["generated_text"][len(prompt):])
`

Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.13s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

Arrrr, shiver me timbers! Me name be Captain Chatbot, the scurviest pirate to ever sail the Seven Seas! Me be a swashbucklin' chatbot, here to regale ye with tales o' adventure, answer yer questions, and maybe even steal yer treasure (just kiddin', matey... or am I?). So hoist the colors and set course for a life o' pirate-y fun with me!

Sun Apr 21 22:20:10 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
|  0%   46C    P8             30W /  450W |   15990MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   1501880      C   /home/zeng/.conda/envs/vllm/bin/python      15984MiB |
+-----------------------------------------------------------------------------------------+

**Comment by jiazi1** [comment]
same problem here. 

Tried to clone from hugging face, got the error 
`SafetensorError: Error while deserializing header: HeaderTooLarge`

**Comment by hjyeeoonng** [comment]
I got the same error

OSError: meta-llama/Meta-Llama-3-8B-Instruct does not appear to have a file named config.json. Checkout 'https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/None' for available files.

I fixed this error by making new download python file
this is example,

[llama3InstructDown.py]
from huggingface_hub import snapshot_download
snapshot_download(repo_id="meta-llama/Meta-Llama-3-8B-Instruct", allow_patterns=["*.json","*.safetensors"], ignore_patterns=[".gitattributes","LICENSE","*.md"])

I was able to solve an OSError in which the model was not downloaded just by executing file llama3InstructDown.py.
I hope this solution will help.

**Comment by khoaguye** [comment]
Hi, how can you resolve this problem?

**Comment by RengGyu** [comment]
`!huggingface-cli download meta-llama/Meta-Llama-3-8B-Instruct --local-dir meta-llama/Meta-Llama-3-8B-Instruct`

I recommend this download way,
then you can get a config.json and the other files!

**Comment by ferrouswheel** [comment]
The fundamental problem is that the official download.sh and huggingface are different distributions of llama models and this is not specified well enough in the documentation.

If you want to use transformers on a locally downloaded model, it's best to download from the huggingface repo and ignore the `download.sh` method.

**Comment by LeMei** [comment]
I also havet the same problem.

**Comment by mostafaelhoushi** [comment]
I had a similar issue and the problem turned out to be the hard disk ran out of space.
