### ISSUE TITLE
Knowledge base cut-off date verification

### ISSUE THREAD

**Issue by RingCanary** [meta-llama/llama3#72]
As per the model, it reports the cut-off date to be December 31st, 2021.

Sample output:
```shell
>>> what's your knowledge base cut-off date?
I was trained until 2021, so my knowledge cutoff is December 31st, 2021. This means ... TRIMMED ...


>>>Ok, what's the last version of python and rust you're aware of?
As my training data cutoff is December 31st, 2021:

* Python: I'm aware of Python 3.9.x, which was released in October 2021. I might not have information on later
versions such as Python 3.10 or 3.11.
* Rust: I'm familiar with Rust 1.53.0, which was the latest version ... TRIMMED ...
```

The model has been taken from ollama's website : https://ollama.com/library/llama3
Model version : Latest (llama3:8b)

**Comment by ejsd1989** [comment]
Hey @RingCanary, thanks for reporting! So, i'm not sure the parameters of your inference, but the best resource for the actual knowledge base cutoff date is the official [MODEL_CARD.md](https://github.com/meta-llama/llama3/blob/main/MODEL_CARD.md). 

As per the model card, the knowledge cutoff for 8B was March 2023.

**Comment by RingCanary** [comment]
Hey @ejsd1989 : Thanks for highlighting, I've reviewed and checked the [MODEL_CARD.md](https://github.com/meta-llama/llama3/blob/main/MODEL_CARD.md) file, thus I was confused why the LLM in chat mode is still giving incorrect info -- considering the erroneous reply is mostly for security reasons. And after a bit of analysis as per the methodolgy explained in [this](https://arxiv.org/pdf/2403.12958.pdf) paper, the knowledge cut-off indeed, appears to be around early 2023 / late 2022.

(It was fun to study such complex model in detail.)
