### ISSUE TITLE
Function Calling 

### ISSUE THREAD

**Issue by krishhrana** [meta-llama/llama3#78]
Does llama-3 support function calling? Based on the demos and the llama-3 website, it seems that it is able to perform function calls, but I could not find any documentation for it

**Comment by ejsd1989** [comment]
Hey @krishhrana, thanks for asking. 

Function calling is not supported by the llama-3 models at this time.

**Comment by ashpreetbedi** [comment]
@krishhrana @ejsd1989 we got function calling working 7/10 with llama3:8b and 9/10 with llama3:70b. Here's the [code](https://github.com/phidatahq/phidata/tree/main/cookbook/llms/ollama/tools) for local llama3:8b. Here's [the code](https://github.com/phidatahq/phidata/blob/main/cookbook/llms/groq/finance.py) doing function calling with llama3:70b on groq.

Demo video of llama3:8b doing spectacular function calls:

https://github.com/meta-llama/llama3/assets/22579644/2a94ca5c-fcdb-4f50-a3a6-0ec71bdbfa44

**Comment by raivatshah** [comment]
great work @ashpreetbedi ! Do you have any evals / statistics on how many times it can mess up the JSON / function calling for example?

**Comment by msamylea** [comment]
Was able to get it working via Ollama with LangChain OllamaFunctions.  Code is here: https://github.com/msamylea/Llama3_Function_Calling/tree/main

**Comment by UmutAlihan** [comment]
Looking very forward to be able to function call with open source models. It doesn't even have to be compatible with how OpenAI emposes the methodology. Another derivative approach of function calling for os models, which really works would be the killer model for the community I preassume:)
