### ISSUE TITLE
Llama-3-8b-chat

### ISSUE THREAD

**Issue by masterofaimoein** [meta-llama/llama3#82]
Will Meta release Lllama-3-8B-chat like llana-2-7B-chat?

**Comment by Jenilshyara1** [comment]
Lllama-3-8B-chat is [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct).
chat version is optimized for dialogue use cases.

**Comment by ejsd1989** [comment]
@masterofaimoein the answer by @Jenilshyara1 is correct. 

The Meta Llama-3 Instruct models are the Llama-3 comparable to the Llama-2 Chat models. 

Please take a look at our [llama-recipes](https://github.com/meta-llama/llama-recipes) repo for examples and getting started quickly!

**Comment by masterofaimoein** [comment]
> hi @masterofaimoein , Lllama-3-8B-chat is [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct).
> chat version is optimized for dialogue use cases.

Thanks for your answering.
When I use GGUF version of llama-3-8B-instruct with llama-cpp-python, llama-3-8B-Instruct give me more that one answer and not give answer to my question, How can I solve that? Do you have any complate guid for use llama-3-8B-Instruct?

**Comment by Jenilshyara1** [comment]
Hello @masterofaimoein , check that you are using the correct prompt for llama-3, check this blog [https://huggingface.co/blog/llama3#how-to-prompt-llama-3](https://huggingface.co/blog/llama3#how-to-prompt-llama-3)

**Comment by masterofaimoein** [comment]
How can I remove system messages and get only main result of user question answer in llama-cpp-python and llama-3-8B-Instruct-GGUF?
