### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by rinekso** [meta-llama/llama3#97]
I try to register and I got the url in my email, and next step, I clone the repository and then run download.sh, input the url and then enter list model to download, but after that I got error ssl connection, response like this :

Connecting to download6.llamameta.net|108.138.141.82|:443... connected.
OpenSSL: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)
Unable to establish SSL connection.

what configuration I need to do?

**Comment by rinekso** [comment]
I'm sorry it just because my wget, I need to upgrade it. silly me.

**Comment by Shadow-CN** [comment]
What's the version of your wget?
